# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - oldrel
  - release
  - devel


r_github_packages:
  - jimhester/lintr


after_success:
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package(".", linters = with_defaults(object_name_linter = NULL))'