// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// ipfp_cpp
arma::mat ipfp_cpp(arma::vec initial_table, arma::colvec row_marginals, arma::rowvec col_marginals, int dimension, int maxiter, double tolerance);
RcppExport SEXP _multgee_ipfp_cpp(SEXP initial_tableSEXP, SEXP row_marginalsSEXP, SEXP col_marginalsSEXP, SEXP dimensionSEXP, SEXP maxiterSEXP, SEXP toleranceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type initial_table(initial_tableSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type row_marginals(row_marginalsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type col_marginals(col_marginalsSEXP);
    Rcpp::traits::input_parameter< int >::type dimension(dimensionSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    rcpp_result_gen = Rcpp::wrap(ipfp_cpp(initial_table, row_marginals, col_marginals, dimension, maxiter, tolerance));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_multgee_ipfp_cpp", (DL_FUNC) &_multgee_ipfp_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_multgee(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
