# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ipfp_cpp <- function(initial_table, row_marginals, col_marginals, dimension, maxiter, tolerance) {
    .Call(`_multgee_ipfp_cpp`, initial_table, row_marginals, col_marginals, dimension, maxiter, tolerance)
}

